name: radio_stations
description: "A single screen app for streaming online radio stations"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  audio_service: ^0.18.17
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  hive_ce: ^2.10.1
  http: ^1.3.0
  json_annotation: ^4.9.0
  just_audio: ^0.9.46
  path_provider: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
